---
# playbook.yml
- name: Provision Zenotta Bare Metal Mining Image
  hosts: default
  become: true

  tasks:
    
    #https://wiki.debian.org/NvidiaGraphicsDrivers#Debian_11_.22Bullseye.22
    # - name: Add nvidia driver repo to sources list
    #   ansible.builtin.apt_repository:
    #     repo: deb http://deb.debian.org/debian/ bullseye main contrib non-free
    #     state: present

    # - name: Install the NVidia drivers
    #   ansible.builtin.apt:
    #     pkg:
    #       - nvidia-driver 
    #       - firmware-misc-nonfree

    # - name: Get NVidia container runtime repo gpg key
    #   ansible.builtin.apt_key:
    #     url: https://nvidia.github.io/nvidia-docker/gpgkey
    
    # - name: Add NVidia container runtime to sources list
    #   apt_repository:
    #     repo: "{{ item }}"
    #     filename: nvidia-container-runtime
    #     state: present
    #     mode: 0644
    #   with_items:
    #     - 'deb https://nvidia.github.io/libnvidia-container/debian11/amd64 /'
    #     - 'deb https://nvidia.github.io/nvidia-container-runtime/debian11/amd64 /'
        
    # - name: Install the NVidia container toolkit for base system
    #   ansible.builtin.apt:
    #     pkg:
    #       - nvidia-container-toolkit-base

    # - name: Generate NVidia CDI specification
    #   command: nvidia-ctk cdi generate --output=/etc/cdi/nvidia.yaml

    - name: Install Podman to run our containers
      ansible.builtin.apt: 
        pkg:
          - slirp4netns
          - fuse-overlayfs
          - podman
          
    - name: Test podman
      shell: podman --version

    - name: Create group for container users
      ansible.builtin.group:
        name: zenotta-miner
        state: present

    - name: Create user for running containers
      ansible.builtin.user:
        name: zenotta-miner
        group: zenotta-miner
        shell: /usr/bin/false

    - name: Create gid and uid ranges
      command: usermod --add-subuids 100000-165535 --add-subgids 100000-165535 zenotta-miner

    - name: Run container
      containers.podman.podman_container:
        name: zenotta-miner
        image: ghcr.io/barryboot/miner-bare-metal:main
        network: slirp4netns
        device: 
          - /dev/fuse
        security_opt:
          - label=disable
          - unmask=ALL
        volume: 
          - /home/zenotta/.local/share/containers
        state: started
        user: zenotta-miner
        debug: true


    