---
# playbook.yml
- name: Provision Zenotta Bare Metal Mining Image
  hosts: default
  become: true

  tasks:
    
    - name: Install Podman to run our containers
      ansible.builtin.apt: 
        pkg:
          - containernetworking-plugins

    #https://wiki.debian.org/NvidiaGraphicsDrivers#Debian_11_.22Bullseye.22
    # - name: Add nvidia driver repo to sources list
    #   ansible.builtin.apt_repository:
    #     repo: deb http://deb.debian.org/debian/ bullseye main contrib non-free
    #     state: present

    # - name: Install the NVidia drivers
    #   ansible.builtin.apt:
    #     pkg:
    #       - nvidia-driver 
    #       - firmware-misc-nonfree

    # - name: Get NVidia container runtime repo gpg key
    #   ansible.builtin.apt_key:
    #     url: https://nvidia.github.io/nvidia-docker/gpgkey
    
    # - name: Add NVidia container runtime to sources list
    #   apt_repository:
    #     repo: "{{ item }}"
    #     filename: nvidia-container-runtime
    #     state: present
    #     mode: 0644
    #   with_items:
    #     - 'deb https://nvidia.github.io/libnvidia-container/debian11/amd64 /'
    #     - 'deb https://nvidia.github.io/nvidia-container-runtime/debian11/amd64 /'
        
    # - name: Install the NVidia container toolkit for base system
    #   ansible.builtin.apt:
    #     pkg:
    #       - nvidia-container-toolkit-base

    # - name: Generate NVidia CDI specification
    #   command: nvidia-ctk cdi generate --output=/etc/cdi/nvidia.yaml

    - name: Run container
      containers.podman.podman_container:
        name: container
        image: quay.io/bitnami/wildfly
        state: started


    